modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="sweetapocalpysebiome"
version="1.5.0"
displayName="SweetApocalpyseBiome"
displayURL="https://www.youtube.com/@wayasteurbaut"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="WayaCreateYT"
description="Sweet Apocalypse Biome Mod Dont get Yourself In A sticky Sitaution"
enumExtensions="META-INF/enumextensions.json"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "sweetapocalpysebiome.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.sweetapocalpysebiome]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sweetapocalpysebiome]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration